[package]
name = "sonettobuf"
version.workspace = true
edition.workspace = true


[dependencies]
prost.workspace = true
prost-types.workspace = true

[build-dependencies]
prost-build.workspace = true
